version: "3.8"
services:
  db:
    image: postgres:15
    container_name: db_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db-postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db-postgres"]
      interval: 5s
      retries: 5
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: lib_container
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres_password
    ports:
      - "8080:8080"

volumes:
  test_postgres_data: