services:
  db:
    image: postgres:15
    container_name: db_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db-postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db-postgres"]
      interval: 5s
      retries: 2
    volumes:
      - lib:/var/lib/postgresql/data
    networks:
      - library_network
  app:
    build: .
    container_name: lib_container
    restart: always
    depends_on:
      - db
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db-postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres_password
    ports:
      - "8080:8888"
    networks:
      - library_network

volumes:
  lib:

networks:
  library_network:
    external: true