services:
  lib_db:
    image: postgres:15
    container_name: lib_db
    environment:
      POSTGRES_USER: ${POSTGRES_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATASOURCE_DB}
    env_file: .env
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DATASOURCE_USERNAME} -d ${POSTGRES_DATASOURCE_DB}"]
      interval: 5s
      retries: 2
    volumes:
      - lib:/var/lib/postgresql/data
    networks:
      - library_network

  lib-app:
    image: lib-image
    build: .
    container_name: lib_container
    restart: always
    depends_on:
      - lib_db
    env_file: .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      SPRING_DATASOURCE_URL: ${POSTGRES_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DATASOURCE_PASSWORD}
    ports:
      - "8080:8888"
    networks:
      - library_network

volumes:
  lib:

networks:
  library_network:
    external: true