server:
  port: 8888
  error:
    include-message: always

spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db-postgres
    username: postgres
    password: postgres_password
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
    url: jdbc:postgresql://localhost:5432/db-postgres
    user: postgres
    password: postgres_password
    parameters:
      user_name: postgres
  main:
    web-application-type: servlet