server:
  port: 8888
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DATASOURCE_URL}
    username: ${POSTGRES_DATASOURCE_USERNAME}
    password: ${POSTGRES_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: ${LIQUIBASE_MAIN_CHANGELOG}
    url: ${POSTGRES_DATASOURCE_URL}
    user: ${POSTGRES_DATASOURCE_USERNAME}
    password: ${POSTGRES_DATASOURCE_PASSWORD}
    parameters:
      user_name: postgres
    drop-first: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  main:
    web-application-type: servlet

feign:
  client:
    config:
      subscription-service:
        url: ${FEIGN_CLIENT_BASEURL}